const products = [
    { id: "1", image: "images/toyota-corolla.jpg", name: "Toyota Corolla", rating: { stars: 4.5, count: 120 }, priceCents: 2000000, keywords: ["Toyota", "Corolla", "sedan", "reliable"] },
    { id: "2", image: "images/honda-civic.jpg", name: "Honda Civic", rating: { stars: 4.7, count: 140 }, priceCents: 2200000, keywords: ["Honda", "Civic", "sedan", "fuel efficient"] },
    { id: "3", image: "images/ford-f150.jpg", name: "Ford F-150", rating: { stars: 4.6, count: 200 }, priceCents: 3000000, keywords: ["Ford", "F-150", "pickup", "utility"] },
    { id: "4", image: "images/chevrolet-silverado.jpg", name: "Chevrolet Silverado", rating: { stars: 4.5, count: 180 }, priceCents: 3200000, keywords: ["Chevrolet", "Silverado", "pickup", "powerful"] },
    { id: "5", image: "images/tesla-model-3.jpg", name: "Tesla Model 3", rating: { stars: 4.8, count: 250 }, priceCents: 5000000, keywords: ["Tesla", "Model 3", "electric", "sedan"] },
    { id: "6", image: "images/nissan-altima.jpg", name: "Nissan Altima", rating: { stars: 4.4, count: 130 }, priceCents: 2300000, keywords: ["Nissan", "Altima", "sedan", "spacious"] },
    { id: "7", image: "images/bmw-3-series.jpg", name: "BMW 3 Series", rating: { stars: 4.7, count: 160 }, priceCents: 4500000, keywords: ["BMW", "3 Series", "luxury", "sedan"] },
    { id: "8", image: "images/audi-a4.jpg", name: "Audi A4", rating: { stars: 4.6, count: 145 }, priceCents: 4700000, keywords: ["Audi", "A4", "luxury", "sedan"] },
    { id: "9", image: "images/mercedes-c-class.jpg", name: "Mercedes-Benz C-Class", rating: { stars: 4.8, count: 150 }, priceCents: 5500000, keywords: ["Mercedes-Benz", "C-Class", "luxury", "sedan"] },
    { id: "10", image: "images/hyundai-sonata.jpg", name: "Hyundai Sonata", rating: { stars: 4.3, count: 110 }, priceCents: 2100000, keywords: ["Hyundai", "Sonata", "sedan", "affordable"] },
    { id: "11", image: "images/kia-optima.jpg", name: "Kia Optima", rating: { stars: 4.4, count: 105 }, priceCents: 2200000, keywords: ["Kia", "Optima", "sedan", "value"] },
    { id: "12", image: "images/toyota-camry.jpg", name: "Toyota Camry", rating: { stars: 4.7, count: 150 }, priceCents: 2400000, keywords: ["Toyota", "Camry", "sedan", "popular"] },
    { id: "13", image: "images/honda-accord.jpg", name: "Honda Accord", rating: { stars: 4.6, count: 160 }, priceCents: 2500000, keywords: ["Honda", "Accord", "sedan", "spacious"] },
    { id: "14", image: "images/ford-mustang.jpg", name: "Ford Mustang", rating: { stars: 4.8, count: 180 }, priceCents: 3500000, keywords: ["Ford", "Mustang", "sports", "coupe"] },
    { id: "15", image: "images/chevrolet-camaro.jpg", name: "Chevrolet Camaro", rating: { stars: 4.7, count: 170 }, priceCents: 3600000, keywords: ["Chevrolet", "Camaro", "sports", "coupe"] },
    { id: "16", image: "images/tesla-model-x.jpg", name: "Tesla Model X", rating: { stars: 4.9, count: 200 }, priceCents: 8000000, keywords: ["Tesla", "Model X", "electric", "SUV"] },
    { id: "17", image: "images/jeep-wrangler.jpg", name: "Jeep Wrangler", rating: { stars: 4.6, count: 190 }, priceCents: 3000000, keywords: ["Jeep", "Wrangler", "SUV", "off-road"] },
    { id: "18", image: "images/toyota-highlander.jpg", name: "Toyota Highlander", rating: { stars: 4.5, count: 140 }, priceCents: 3500000, keywords: ["Toyota", "Highlander", "SUV", "family"] },
    { id: "19", image: "images/honda-pilot.jpg", name: "Honda Pilot", rating: { stars: 4.5, count: 125 }, priceCents: 3600000, keywords: ["Honda", "Pilot", "SUV", "family"] },
    { id: "20", image: "images/ford-escape.jpg", name: "Ford Escape", rating: { stars: 4.4, count: 100 }, priceCents: 2700000, keywords: ["Ford", "Escape", "SUV", "compact"] },
    { id: "21", image: "images/mazda-cx-5.jpg", name: "Mazda CX-5", rating: { stars: 4.5, count: 110 }, priceCents: 2800000, keywords: ["Mazda", "CX-5", "SUV", "compact"] },
    { id: "22", image: "images/subaru-outback.jpg", name: "Subaru Outback", rating: { stars: 4.6, count: 120 }, priceCents: 3200000, keywords: ["Subaru", "Outback", "SUV", "all-wheel drive"] },
    { id: "23", image: "images/toyota-rav4.jpg", name: "Toyota RAV4", rating: { stars: 4.7, count: 140 }, priceCents: 3400000, keywords: ["Toyota", "RAV4", "SUV", "popular"] },
    { id: "24", image: "images/honda-crv.jpg", name: "Honda CR-V", rating: { stars: 4.6, count: 130 }, priceCents: 3300000, keywords: ["Honda", "CR-V", "SUV", "compact"] },
    { id: "25", image: "images/volkswagen-jetta.jpg", name: "Volkswagen Jetta", rating: { stars: 4.3, count: 100 }, priceCents: 2200000, keywords: ["Volkswagen", "Jetta", "sedan", "German"] },
    { id: "26", image: "images/chevrolet-traverse.jpg", name: "Chevrolet Traverse", rating: { stars: 4.5, count: 115 }, priceCents: 3700000, keywords: ["Chevrolet", "Traverse", "SUV", "family"] },
    { id: "27", image: "images/jeep-grand-cherokee.jpg", name: "Jeep Grand Cherokee", rating: { stars: 4.6, count: 140 }, priceCents: 4000000, keywords: ["Jeep", "Grand Cherokee", "SUV", "luxury"] },
    { id: "28", image: "images/mercedes-gle.jpg", name: "Mercedes-Benz GLE", rating: { stars: 4.8, count: 150 }, priceCents: 7000000, keywords: ["Mercedes-Benz", "GLE", "SUV", "luxury"] },
    { id: "29", image: "images/bmw-x5.jpg", name: "BMW X5", rating: { stars: 4.7, count: 145 }, priceCents: 6900000, keywords: ["BMW", "X5", "SUV", "luxury"] },
    { id: "30", image: "images/audi-q5.jpg", name: "Audi Q5", rating: { stars: 4.6, count: 135 }, priceCents: 6800000, keywords: ["Audi", "Q5", "SUV", "luxury"] },
    { id: "31", image: "images/tesla-model-y.jpg", name: "Tesla Model Y", rating: { stars: 4.9, count: 200 }, priceCents: 7500000, keywords: ["Tesla", "Model Y", "electric", "SUV"] },
    { id: "32", image: "images/toyota-4runner.jpg", name: "Toyota 4Runner", rating: { stars: 4.5, count: 120 }, priceCents: 4200000, keywords: ["Toyota", "4Runner", "SUV", "off-road"] },
    { id: "33", image: "images/honda-fit.jpg", name: "Honda Fit", rating: { stars: 4.4, count: 110 }, priceCents: 1600000, keywords: ["Honda", "Fit", "compact", "hatchback"] },
    { id: "34", image: "images/ford-explorer.jpg", name: "Ford Explorer", rating: { stars: 4.5, count: 130 }, priceCents: 4300000, keywords: ["Ford", "Explorer", "SUV", "family"] },
    { id: "35", image: "images/chevrolet-equinox.jpg", name: "Chevrolet Equinox", rating: { stars: 4.4, count: 125 }, priceCents: 2900000, keywords: ["Chevrolet", "Equinox", "SUV", "compact"] },
    { id: "36", image: "images/kia-sportage.jpg", name: "Kia Sportage", rating: { stars: 4.4, count: 120 }, priceCents: 2500000, keywords: ["Kia", "Sportage", "SUV", "affordable"] },
    { id: "37", image: "images/hyundai-tucson.jpg", name: "Hyundai Tucson", rating: { stars: 4.4, count: 115 }, priceCents: 2600000, keywords: ["Hyundai", "Tucson", "SUV", "compact"] },
    { id: "38", image: "images/ford-bronco.jpg", name: "Ford Bronco", rating: { stars: 4.7, count: 150 }, priceCents: 4500000, keywords: ["Ford", "Bronco", "SUV", "off-road"] },
    { id: "39", image: "images/nissan-rogue.jpg", name: "Nissan Rogue", rating: { stars: 4.4, count: 125 }, priceCents: 2700000, keywords: ["Nissan", "Rogue", "SUV", "compact"] },
    { id: "40", image: "images/toyota-sienna.jpg", name: "Toyota Sienna", rating: { stars: 4.6, count: 110 }, priceCents: 4500000, keywords: ["Toyota", "Sienna", "minivan", "family"] },
    { id: "41", image: "images/honda-odyssey.jpg", name: "Honda Odyssey", rating: { stars: 4.6, count: 120 }, priceCents: 4400000, keywords: ["Honda", "Odyssey", "minivan", "family"] },
    { id: "42", image: "images/chrysler-pacifica.jpg", name: "Chrysler Pacifica", rating: { stars: 4.5, count: 115 }, priceCents: 4600000, keywords: ["Chrysler", "Pacifica", "minivan", "luxury"] },
    { id: "43", image: "images/chevrolet-suburban.jpg", name: "Chevrolet Suburban", rating: { stars: 4.6, count: 110 }, priceCents: 6000000, keywords: ["Chevrolet", "Suburban", "SUV", "large"] },
    { id: "44", image: "images/ford-expedition.jpg", name: "Ford Expedition", rating: { stars: 4.5, count: 100 }, priceCents: 6100000, keywords: ["Ford", "Expedition", "SUV", "large"] },
    { id: "45", image: "images/nissan-sentra.jpg", name: "Nissan Sentra", rating: { stars: 4.3, count: 90 }, priceCents: 1800000, keywords: ["Nissan", "Sentra", "sedan", "compact"] },
    { id: "46", image: "images/hyundai-elantra.jpg", name: "Hyundai Elantra", rating: { stars: 4.4, count: 95 }, priceCents: 1900000, keywords: ["Hyundai", "Elantra", "sedan", "compact"] },
    { id: "47", image: "images/volkswagen-atlas.jpg", name: "Volkswagen Atlas", rating: { stars: 4.5, count: 105 }, priceCents: 5000000, keywords: ["Volkswagen", "Atlas", "SUV", "family"] },
    { id: "48", image: "images/mazda-mazda3.jpg", name: "Mazda Mazda3", rating: { stars: 4.4, count: 115 }, priceCents: 2100000, keywords: ["Mazda", "Mazda3", "sedan", "compact"] },
    { id: "49", image: "images/chevrolet-blazer.jpg", name: "Chevrolet Blazer", rating: { stars: 4.5, count: 100 }, priceCents: 3100000, keywords: ["Chevrolet", "Blazer", "SUV", "compact"] },
    { id: "50", image: "images/audi-a6.jpg", name: "Audi A6", rating: { stars: 4.8, count: 130 }, priceCents: 7000000, keywords: ["Audi", "A6", "luxury", "sedan"] },
  ];
  